// <auto-generated />
using System;
using Lotofacil.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lotofacil.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241130113328_Mudando atributos da classe BaseContest")]
    partial class MudandoatributosdaclasseBaseContest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lotofacil.Domain.Entities.BaseContest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<int>("Hit11")
                        .HasColumnType("int")
                        .HasColumnName("Hit11");

                    b.Property<int>("Hit12")
                        .HasColumnType("int")
                        .HasColumnName("Hit12");

                    b.Property<int>("Hit13")
                        .HasColumnType("int")
                        .HasColumnName("Hit13");

                    b.Property<int>("Hit14")
                        .HasColumnType("int")
                        .HasColumnName("Hit14");

                    b.Property<int>("Hit15")
                        .HasColumnType("int")
                        .HasColumnName("Hit15");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.Property<string>("Numbers")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("Numbers");

                    b.HasKey("Id");

                    b.ToTable("BaseContest", (string)null);
                });

            modelBuilder.Entity("Lotofacil.Domain.Entities.Contest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseContestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<DateTime?>("LastProcessed")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastProcessed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.Property<string>("Numbers")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("Numbers");

                    b.HasKey("Id");

                    b.HasIndex("BaseContestId");

                    b.ToTable("Contest", (string)null);
                });

            modelBuilder.Entity("Lotofacil.Domain.Entities.ContestActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BaseContestName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("BaseContestName");

                    b.Property<string>("BaseContestNumbers")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("BaseContestNumbers");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateTime");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<bool>("MatchedAnyBaseContest")
                        .HasColumnType("bit")
                        .HasColumnName("MatchedAnyBaseContest");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.Property<string>("Numbers")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("Numbers");

                    b.HasKey("Id");

                    b.ToTable("ContestActivityLog", (string)null);
                });

            modelBuilder.Entity("Lotofacil.Domain.Entities.Contest", b =>
                {
                    b.HasOne("Lotofacil.Domain.Entities.BaseContest", null)
                        .WithMany("ContestsAbove11")
                        .HasForeignKey("BaseContestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Lotofacil.Domain.Entities.BaseContest", b =>
                {
                    b.Navigation("ContestsAbove11");
                });
#pragma warning restore 612, 618
        }
    }
}
