// <auto-generated />
using System;
using Lotofacil.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lotofacil.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241020131750_Correção do tamanho das strings do números dos concursos das entidades")]
    partial class Correçãodotamanhodasstringsdonúmerosdosconcursosdasentidades
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Lotofacil.Models.BaseContest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BaseNumbers")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("BaseNumbers");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<int>("Matched11")
                        .HasColumnType("int");

                    b.Property<int>("Matched12")
                        .HasColumnType("int");

                    b.Property<int>("Matched13")
                        .HasColumnType("int");

                    b.Property<int>("Matched14")
                        .HasColumnType("int");

                    b.Property<int>("Matched15")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("BaseContests");
                });

            modelBuilder.Entity("Lotofacil.Models.Contest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BaseContestId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<string>("DrawnNumbers")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("DrawnNumbers");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.HasIndex("BaseContestId");

                    b.ToTable("Contests");
                });

            modelBuilder.Entity("Lotofacil.Models.Contest", b =>
                {
                    b.HasOne("Lotofacil.Models.BaseContest", null)
                        .WithMany("ContestsAbove11")
                        .HasForeignKey("BaseContestId");
                });

            modelBuilder.Entity("Lotofacil.Models.BaseContest", b =>
                {
                    b.Navigation("ContestsAbove11");
                });
#pragma warning restore 612, 618
        }
    }
}
