// <auto-generated />
using System;
using Lotofacil.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lotofacil.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240929213945_Alteração no atributo de data de ambas as classes")]
    partial class Alteraçãonoatributodedatadeambasasclasses
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Lotofacil.Models.Concurso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Nome");

                    b.Property<string>("NumerosSorteados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NumerosConcurso");

                    b.HasKey("Id");

                    b.ToTable("Concursos");
                });

            modelBuilder.Entity("Lotofacil.Models.ConcursoBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Acertou11")
                        .HasColumnType("int");

                    b.Property<int>("Acertou12")
                        .HasColumnType("int");

                    b.Property<int>("Acertou13")
                        .HasColumnType("int");

                    b.Property<int>("Acertou14")
                        .HasColumnType("int");

                    b.Property<int>("Acertou15")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime2")
                        .HasColumnName("Data");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("Nome");

                    b.Property<string>("NumerosBase")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NumerosConcursoBase");

                    b.HasKey("Id");

                    b.ToTable("ConcursosBase");
                });
#pragma warning restore 612, 618
        }
    }
}
